version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - NODE_ENV=production
      - VITE_API_URL=https://api.moneybox.com/api
    depends_on:
      - backend
    networks:
      - moneybox-prod
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - config/production.env
    volumes:
      - prod-data:/app/server/data
      - prod-uploads:/app/server/uploads
    networks:
      - moneybox-prod
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - moneybox-prod
    deploy:
      restart_policy:
        condition: on-failure

  # Production monitoring
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - moneybox-prod

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - moneybox-prod

networks:
  moneybox-prod:
    driver: overlay

volumes:
  prod-data:
  prod-uploads:
  grafana-data:
