version: '3.8'

services:
  # Frontend (React + Vite)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - VITE_API_URL=http://backend:3002/api
    depends_on:
      - backend
    networks:
      - moneybox-network

  # Backend (Node.js + Express)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - CORS_ORIGIN=http://localhost:3000
    volumes:
      - ./server/data:/app/server/data
      - ./server/uploads:/app/server/uploads
    networks:
      - moneybox-network

  # Nginx reverse proxy (for production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - moneybox-network

networks:
  moneybox-network:
    driver: bridge

volumes:
  data-volume:
  uploads-volume:
